services: 
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5445:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
volumes:
  postgres_data_dev:
    name : postgres_data_dev