/**
 * Shared Types Package
 *
 * This package contains shared TypeScript types used across the monorepo.
 * Types are auto-generated from the Prisma schema and supplemented with utility types.
 *
 * [AI-GENERATED] - This file is auto-generated by MoonForge based on the Prisma schema.
 * When the schema changes, this file will be regenerated to include new models and fields.
 * DO NOT edit the Prisma type exports section manually.
 */

// ============================================================================
// Prisma Generated Types
// ============================================================================
// [AI-GENERATED SECTION START]
// The AI will populate this section with re-exports from the Prisma client
// Example format (AI should replace with actual models):
//
// export type { User, Project, Post, Comment } from '../../apps/api/prisma/schema.prisma';
//
// After generating the Prisma schema, export all model types here:
// export type { /* all model names */ } from '../../apps/api/generated/prisma/index.js';
// [AI-GENERATED SECTION END]

// Placeholder re-export - AI will replace this with actual model exports
export type {} from "../../apps/api/generated/prisma/index.js";

// ============================================================================
// Utility Types
// ============================================================================

/**
 * Make specific properties optional
 */
export type PartialBy<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

/**
 * Make all properties required
 */
export type RequiredAll<T> = {
	[P in keyof T]-?: T[P];
};

/**
 * Extract element type from array
 */
export type ArrayElement<T> = T extends readonly (infer E)[] ? E : never;

/**
 * Make specific properties required, keeping the rest optional
 */
export type RequiredOnly<T, K extends keyof T> = T & Required<Pick<T, K>>;

// ============================================================================
// API Response Types
// ============================================================================

/**
 * Standard API success response
 */
export interface ApiResponse<T> {
	success: true;
	data: T;
	meta: {
		timestamp: string;
		[key: string]: unknown;
	};
}

/**
 * Standard API error response
 */
export interface ApiError {
	success: false;
	error: {
		code: string;
		message: string;
		details?: unknown;
	};
	meta: {
		timestamp: string;
	};
}

/**
 * API response type (union of success and error)
 */
export type ApiResult<T> = ApiResponse<T> | ApiError;

// ============================================================================
// Pagination Types
// ============================================================================

/**
 * Pagination query parameters
 */
export interface PaginationParams {
	page: number;
	limit: number;
}

/**
 * Paginated response wrapper
 */
export interface PaginatedResponse<T> {
	items: T[];
	pagination: {
		page: number;
		limit: number;
		total: number;
		totalPages: number;
	};
}

// ============================================================================
// Common Types
// ============================================================================

/**
 * UUID string type
 */
export type UUID = string;

/**
 * ISO datetime string
 */
export type ISO8601 = string;

/**
 * Entity with timestamps
 */
export interface Timestamped {
	createdAt: Date;
	updatedAt: Date;
}

/**
 * Soft-deleteable entity
 */
export interface SoftDeletable extends Timestamped {
	deletedAt?: Date;
}
