/**
 * MoonForge Generator
 * Core package for generating MoonForge monorepo projects
 */

// ============================================================================
// Types
// ============================================================================

/**
 * File source tracking for UI labeling
 * - template: Direct copy from template
 * - ai_generated: Generated by AI
 * - modified: Changed by user via refine
 */
export type FileSource = "template" | "ai_generated" | "modified";

/**
 * Represents a generated file in the project
 */
export interface GeneratedFile {
	/** Relative path from project root, e.g., "apps/api/src/index.ts" */
	path: string;
	/** File content (or base64 for binary files) */
	content: string;
	/** Source tracking for UI labeling */
	source: FileSource;
	/** Whether this file is binary (content is base64 encoded) */
	isBinary?: boolean;
}

/**
 * Options for project generation
 */
export interface GenerateOptions {
	/** Project name (e.g., "My SaaS App") */
	projectName: string;
	/** Project description in natural language */
	projectDescription: string;
	/** Optional: specific modules to include */
	modules?: string[];
}

/**
 * Result of project generation
 */
export interface GeneratedProject {
	/** Unique project ID */
	id: string;
	/** Project name */
	name: string;
	/** Project slug (sanitized name for directory) */
	slug: string;
	/** All generated files */
	files: GeneratedFile[];
	/** Generation metadata */
	meta: {
		generatedAt: string;
		templateVersion: string;
		totalFiles: number;
		aiGeneratedFiles: number;
		templateFiles: number;
	};
}

/**
 * Query parameters for list endpoints
 */
export interface ListProjectsQuery {
	status?: "draft" | "generated" | "refined";
	orderBy?: "created_at" | "updated_at" | "name";
	order?: "asc" | "desc";
}

// ============================================================================
// Core Functions (implemented in separate modules)
// ============================================================================

export {
	generateMockModules,
	generateMockPrismaSchema,
	generateMockTypes,
} from "./ai-generator.js";
export {
	buildProjectStructure,
	generateRootConfigFiles,
	getFolderStructure,
	isValidOutputPath,
	sanitizeProjectName,
	transformTemplatePaths,
	validateProjectName,
} from "./builder.js";
// File storage and template merge utilities
export {
	decodeBinaryContent,
	encodeBinaryContent,
	type FileSummary,
	isBinaryFile,
	isValidPath,
	type MergeOptions,
	type MergeResult,
	mergeForRefine,
	mergeWithTemplate,
	normalizePath,
	summarizeFiles,
	type TemplateFile,
	truncateContent,
} from "./files.js";
export {
	applySelectiveOverrides,
	filterFilesBySource,
	getMergeStats,
	markFilesAsModified,
	mergeTemplateWithAI,
	mergeWithConflictTracking,
	REQUIRED_PROJECT_FILES,
	validateMergeResult,
} from "./merge.js";
export {
	loadTemplateComponent,
	loadTemplateFile,
	loadTemplateFiles,
} from "./template-loader.js";
export { createProjectZip, getZipMetadata } from "./zipper.js";
