/**
 * Template Merger
 * Core logic for merging template base with AI-generated content
 */

import type { GeneratedFile } from "./index.js";

/**
 * Merge template files with AI-generated files
 * AI content takes priority over template content on the same path
 *
 * @param templateFiles - Files loaded from template
 * @param aiFiles - Files generated by AI
 * @returns Merged array of files with source tracking
 */
export function mergeTemplateWithAI(
	templateFiles: GeneratedFile[],
	aiFiles: GeneratedFile[],
): GeneratedFile[] {
	const result = new Map<string, GeneratedFile>();

	// 1. Add all template files first
	for (const file of templateFiles) {
		result.set(file.path, { ...file, source: "template" });
	}

	// 2. Add/override with AI files (AI takes priority)
	for (const file of aiFiles) {
		result.set(file.path, { ...file, source: "ai_generated" });
	}

	return Array.from(result.values());
}

/**
 * Mark specific files as modified (after user edits in refine flow)
 */
export function markFilesAsModified(
	files: GeneratedFile[],
	modifiedPaths: Set<string>,
): GeneratedFile[] {
	return files.map((file) => ({
		...file,
		source: modifiedPaths.has(file.path) ? "modified" : file.source,
	}));
}

/**
 * Get files by source type
 */
export function filterFilesBySource(
	files: GeneratedFile[],
	source: "template" | "ai_generated" | "modified",
): GeneratedFile[] {
	return files.filter((file) => file.source === source);
}

/**
 * Get statistics about merged files
 */
export function getMergeStats(files: GeneratedFile[]): {
	total: number;
	template: number;
	aiGenerated: number;
	modified: number;
	binary: number;
} {
	return {
		total: files.length,
		template: filterFilesBySource(files, "template").length,
		aiGenerated: filterFilesBySource(files, "ai_generated").length,
		modified: filterFilesBySource(files, "modified").length,
		binary: files.filter((f) => f.isBinary).length,
	};
}

/**
 * Merge with conflict resolution
 * Useful when you want to track conflicts between template and AI content
 */
export interface MergeConflict {
	path: string;
	templateContent: string | null;
	aiContent: string | null;
	resolvedContent: string;
	resolvedSource: "template" | "ai_generated";
}

export function mergeWithConflictTracking(
	templateFiles: GeneratedFile[],
	aiFiles: GeneratedFile[],
): {
	mergedFiles: GeneratedFile[];
	conflicts: MergeConflict[];
} {
	const mergedFiles: GeneratedFile[] = [];
	const conflicts: MergeConflict[] = [];
	const templateMap = new Map(templateFiles.map((f) => [f.path, f]));

	// Add all AI files (and track conflicts with template)
	for (const aiFile of aiFiles) {
		const templateFile = templateMap.get(aiFile.path);

		if (templateFile && templateFile.content !== aiFile.content) {
			// Conflict detected
			conflicts.push({
				path: aiFile.path,
				templateContent: templateFile.content,
				aiContent: aiFile.content,
				resolvedContent: aiFile.content, // AI wins by default
				resolvedSource: "ai_generated",
			});
		}

		mergedFiles.push({ ...aiFile, source: "ai_generated" });
	}

	// Add template files that weren't overridden by AI
	for (const templateFile of templateFiles) {
		const existsInAI = aiFiles.some((f) => f.path === templateFile.path);
		if (!existsInAI) {
			mergedFiles.push({ ...templateFile, source: "template" });
		}
	}

	return { mergedFiles, conflicts };
}

/**
 * Apply selective overrides
 * Allows overriding only specific parts of files while preserving the rest
 */
export function applySelectiveOverrides(
	baseFiles: GeneratedFile[],
	overrides: Map<string, Partial<GeneratedFile>>,
): GeneratedFile[] {
	return baseFiles.map((file) => {
		const override = overrides.get(file.path);
		if (override) {
			return { ...file, ...override };
		}
		return file;
	});
}

/**
 * Validate merge result
 * Ensures no critical files are missing
 */
export function validateMergeResult(
	files: GeneratedFile[],
	requiredPaths: string[],
): {
	valid: boolean;
	missingFiles: string[];
} {
	const existingPaths = new Set(files.map((f) => f.path));
	const missingFiles = requiredPaths.filter((p) => !existingPaths.has(p));

	return {
		valid: missingFiles.length === 0,
		missingFiles,
	};
}

/**
 * Required files for a valid MoonForge project
 */
export const REQUIRED_PROJECT_FILES = [
	"package.json",
	"pnpm-workspace.yaml",
	"apps/api/package.json",
	"apps/api/src/index.ts",
	"apps/api/prisma/schema.prisma",
	"apps/platform/package.json",
	"packages/types/package.json",
];
